# To see the complete list of configurable parameters see:
# https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py

# === GENERAL ===
framework: "torch"
num_workers: 1
num_gpus: 0
num_gpus_per_worker: 1
num_cpus_per_worker: 4
rollout_fragment_length: 200 # 16
timesteps_per_iteration: 0
train_batch_size: 64
learning_starts: 10 #1000
buffer_size: 250000
horizon: 250
lr: 0.0025

# "batch_mode": "complete_episodes"

# === RAINBOW ===
num_atoms: 51 # more than 1
v_min: -10.0 # TODO: set v_min and v_max according to your expected range of returns
v_max: 10.0
noisy: True
dueling: True
double_q: True
n_step: 2 # between 1 and 10
prioritized_replay: True

# === EXPLORATION ===
# "exploration_config": {
#   "type": "EpsilonGreedy",
#   "initial_epsilon": 1.0,
#   "final_epsilon": 0.02,
#   "epsilon_timesteps": 2000000
# }
exploration_config: {
  type: "SoftQ",
  temperature: 1.0,
}

# === NETWORK ===
# hiddens: [256, 512]
# model: {
#   dim: 300,
#   conv_filters: [
#     [16, [5, 5], 4],
#     [32, [5, 5], 2],
#     [32, [5, 5], 2],
#     [64, [5, 5], 1],
#     [64, [5, 5], 2],
#     [128, [5, 5], 2],
#     [512, [5, 5], 1],
#   ]
# }

# === CUSTOM MODEL ===
model:
  custom_model: "custom_dqn_network"
  custom_model_config: {}
  fcnet_hiddens: [64, 64, 4]
  fcnet_activation:
  conv_activation:
  dim: 1000

# === EVALUATION ===
evaluation_interval: 0
evaluation_num_episodes: 0
evaluation_num_workers: 0
evaluation_config:
  env_config:
  explore: False

# === ENVIRONMENT ===
env_config:
  carla:
    host: "localhost"
    timeout: 30.0
    timestep: 0.05
    retries_on_error: 25
    resolution_x: 600
    resolution_y: 400
    quality_level: "Epic"
    enable_map_assets: True
    enable_rendering: True
    show_display: True
    debug_mode: 1
  experiment:
    hero:
      routes: "routes/failed_routes/town05_long/stuck_vehicle_1.xml" #town01_short/red_light_1.xml"
      scenarios: "scenarios/all_towns_traffic_scenarios_WOR.json"
      repetitions: 1
      debug_mode: 1
      ego_vehicle_type: "vehicle.lincoln.mkz2017"
      sensors:
        birdview:
          type: "sensor.birdview"
          size: 300
          radius: 15
        front_camera:
          type: "sensor.camera.rgb"
          image_size_x: 400 # width
          image_size_y: 300 # height
          fov: 100 # degrees
          lens_circle_multiplier: 3.0
          lens_circle_falloff: 3.0
          chromatic_aberration_intensity: 0.5
          chromatic_aberration_offset: 0
        gps:
          type: "sensor.other.gnss"
          noise_alt_stddev: 0.000005
          noise_lat_stddev: 0.000005
          noise_lon_stddev: 0.000005
          noise_alt_bias: 0.0
          noise_lat_bias : 0.0
          noise_lon_bias: 0.0
        imu:
          type: "sensor.other.imu"
          noise_accel_stddev_x: 0.001
          noise_accel_stddev_y: 0.001
          noise_accel_stddev_z: 0.015
          noise_gyro_stddev_x: 0.001
          noise_gyro_stddev_y: 0.001
          noise_gyro_stddev_z: 0.001
    background_activity:
      tm_hybrid_mode: True
    town: "Town05"
    others:
      framestack: 4
      max_time_idle: 600
      max_time_episode: 100 #6400